server:
  port: 8081

ppojin_gw:
  hostname: http://localhost:8081
  keycloak:
    uri: http://localhost:8080
  httpbin:
    uri: http://localhost:8088


spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://app.ppojin.localhost:30080/realms/ppojin