server:
  port: 8081

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/ppojin
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

ppojin_gw:
  keycloak:
    uri: http://localhost:8080
  httpbin:
    uri: http://localhost:8888

## TODO: ADD zipkin
#management:
#  tracing:
#    sampling:
#      probability: 1.0
#    propagation:
#      consume: b3
#      produce: b3_multi
#  zipkin:
#    tracing:
#      endpoint: "http://localhost:9411/api/v2/spans"
#
#logging:
#  pattern:
#    level: "%5p [%X{traceId:-},%X{spanId:-}]"

app:
  security:
    clientId: test-api

logging:
  level:
    org.springframework.security: TRACE
