server:
  port: 8081

ppojin_gw:
  hostname: http://localhost:8081
  keycloak:
    uri: http://localhost:8080
  httpbin:
    uri: http://localhost:8088


spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${ppojin_gw.hostname}/realms/ppojin

logging:
  level:
    feign: TRACE
#    org.springframework.security: TRACE