ppojin_gw:
  keycloak:
    uri: http://keycloak.default.svc:8080
  httpbin:
    uri: http://httpbin.default.svc:8080

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${ppojin_gw.keycloak.uri}/realms/ppojin
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: keycloak
          uri: ${ppojin_gw.keycloak.uri}
          predicates:
            - Path=/realms/**,/resources/**,/robots.txt
          filters:
            - name: LoggingFilter
              args:
                preLogger: 'true'
                postLogger: 'true'
                baseMessage: My Custom Message

## TODO: ADD zipkin
#management:
#  tracing:
#    sampling:
#      probability: 1.0
#    propagation:
#      consume: b3
#      produce: b3_multi
#  zipkin:
#    tracing:
#      endpoint: "http://localhost:9411/api/v2/spans"
#
#logging:
#  pattern:
#    level: "%5p [%X{traceId:-},%X{spanId:-}]"

app:
  security:
    clientId: test-api

logging:
  level:
    org.springframework.security: TRACE
